version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-3-container
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: messaging
      MYSQL_USER: root_test
      MYSQL_PASSWORD: root_test
    ports:
      - "3306:3306"
#  tomcat:
#    image: tomcat:latest
#    container_name: tomcat-3-container
#    networks:
#      - mynetwork
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#    volumes:
#      - /Users/edwingiovanni/Desktop/DEV/FREELANCER/GOVA/messagingService/target/messaging-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/messaging-1.0-SNAPSHOT.war

networks:
  mynetwork:
    driver: bridge