version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: messaging
    ports:
      - "5432:5432"
#  redis:
#    image: redis:latest
#    container_name: redis-container
#    ports:
#      - "6379:6379"

networks:
  mynetwork:
    driver: bridge
